language: php

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer global require hirak/prestissimo
    - composer install --no-interaction --prefer-dist

script:
    - composer lint
    - composer test
